
package ru.javaops.masterjava.service.mail.auto;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MailService", targetNamespace = "http://mail.javaops.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailService {


    /**
     * 
     * @param subject
     * @param to
     * @param body
     * @return
     *     returns ru.javaops.masterjava.service.mail.auto.GroupResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendBulk", targetNamespace = "http://mail.javaops.ru/", className = "ru.javaops.masterjava.service.mail.auto.SendBulk")
    @ResponseWrapper(localName = "sendBulkResponse", targetNamespace = "http://mail.javaops.ru/", className = "ru.javaops.masterjava.service.mail.auto.SendBulkResponse")
    @Action(input = "http://mail.javaops.ru/MailService/sendBulkRequest", output = "http://mail.javaops.ru/MailService/sendBulkResponse")
    public GroupResult sendBulk(
        @WebParam(name = "to", targetNamespace = "")
        List<Addressee> to,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "body", targetNamespace = "")
        String body);

    /**
     * 
     * @param cc
     * @param subject
     * @param to
     * @param body
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendToGroup", targetNamespace = "http://mail.javaops.ru/", className = "ru.javaops.masterjava.service.mail.auto.SendToGroup")
    @ResponseWrapper(localName = "sendToGroupResponse", targetNamespace = "http://mail.javaops.ru/", className = "ru.javaops.masterjava.service.mail.auto.SendToGroupResponse")
    @Action(input = "http://mail.javaops.ru/MailService/sendToGroupRequest", output = "http://mail.javaops.ru/MailService/sendToGroupResponse")
    public String sendToGroup(
        @WebParam(name = "to", targetNamespace = "")
        List<Addressee> to,
        @WebParam(name = "cc", targetNamespace = "")
        List<Addressee> cc,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "body", targetNamespace = "")
        String body);

}
